### ISSUE TITLE
EKS INSTALL Terraform issue

### ISSUE THREAD

**Issue by emre141** [kubernauts/tk8#100]
Hi,
I have trying to install EKS cluster on AWS and using TK8 repository as following EKS installation content.But i when i execute below command i have get a terraform error.

○ → pwd
/opt/kubernetes

 2019-05-02 23:09:20 ⌚  cloudyanke in /opt/kubernetes

Cloning into 'eks'...
                                                                                                    
 _            _                                       _                   _                    _  _ 
| | __ _   _ | |__    ___  _ __  _ __    __ _  _   _ | |_  ___       ___ | | __ ___       ___ | |(_)
| |/ /| | | || '_ \  / _ \| '__|| '_ \  / _` || | | || __|/ __|     / _ \| |/ // __|     / __|| || |
|   < | |_| || |_) ||  __/| |   | | | || (_| || |_| || |_ \__ \    |  __/|   < \__ \    | (__ | || |
|_|\_\ \__,_||_.__/  \___||_|   |_| |_| \__,_| \__,_| \__||___/     \___||_|\_\|___/     \___||_||_|

Found kubectl at /usr/bin/kubectl
2019/05/02 23:05:33 Client Version: v1.13.4

2019/05/02 23:05:33 Terraform binary exists in the installation folder, terraform version:
2019/05/02 23:05:33 Terraform v0.11.13

2019/05/02 23:05:33 starting terraform init
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
2019/05/02 23:05:33 starting terraform apply

Error: No configuration files found!

Apply requires configuration to be present. Applying without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, please run 'terraform destroy' which
does not require any configuration files.

2019/05/02 23:05:33 Exporting kubeconfig file to the installation folder
2019/05/02 23:05:33 To use the kubeconfig file, do the following:
2019/05/02 23:05:33 export KUBECONFIG=~/inventory/TK8EKS/provisioner/kubeconfig
2019/05/02 23:05:33 Exporting Worker nodes config-map to the installation folder
2019/05/02 23:05:33 Creating Worker Nodes
error: no objects passed to apply
2019/05/02 23:05:33 Worker nodes are coming up one by one, it will take some time depending on the number of worker nodes you specified

○ → ls
aws-iam-authenticator  config.yaml  inventory  provisioner  terraform  tk8.pem

When i investigate common.go file the terraform init command command trying to run wrong path so terraform show us to i could not initialized configuration files.

2019-05-02 23:08:19 ⌚  cloudyanke in /opt/kubernetes/inventory/TK8EKS/provisioner/eks
○ → terraform  init
Initializing modules...
- module.eks
  Getting source "./modules/eks"

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (2.8.0)...
- Downloading plugin for provider "http" (1.1.1)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 2.8"
* provider.http: version = "~> 1.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**Comment by arashkaffamanesh** [comment]
Hmm, okay, we'll take care.
But in the meanwhile with 0.7.x release and our lovely Rancher, EKS support can be provided through TPR2 (?).
@ipochi @ishantanu ?

**Comment by ishantanu** [comment]
@arashkaffamanesh Yes, EKS support can be provided via TPR2.

**Comment by ishantanu** [comment]
@ipochi If you're working on this, let me know if you need any information from my side.

**Comment by ishantanu** [comment]
Ongoing investigation with the issue related to the underlying provider - https://github.com/terraform-providers/terraform-provider-rancher2/issues/43.

**Comment by ishantanu** [comment]
Fixed via #113
