### ISSUE TITLE
Replace all instances of sed with strings.Replace(r) function

### ISSUE THREAD

**Issue by arush-sal** [kubernauts/tk8#12]
Problem: As described [here](https://stackoverflow.com/questions/19456518/invalid-command-code-despite-escaping-periods-using-sed) OSX version of `sed` behaves a little different than the Linux variant which can cause certain abnomilities in the code. Therefore we need to replace usage `sed` with a golang native solution.

Example solutions:
https://gist.github.com/tdegrunt/045f6b3377f3f7ffa408
https://gist.github.com/dallarosa/b58b0e3425761e0a7cf6
https://socketloop.com/tutorials/golang-read-a-text-file-and-replace-certain-words

**Comment by frezbo** [comment]
Would it not be better to properly parse the YML files as a data structure rather than `sed` or `String` replace methods which are more error prone

**Comment by arush-sal** [comment]
@frezbo Since the cli is parsing multiple type of files therefore we will have to use the String.Replace(r) function

**Comment by arush-sal** [comment]
@MuellerMH This is not needed anymore as we are using templates now. This can be closed.
