### ISSUE TITLE
Flag control contradiction

### ISSUE THREAD

**Issue by MuellerMH** [kubernauts/tk8#33]
Flags in general are used to report deviations from the standard.  For example, you could tell the CLI where to look for a config or which OS to use. 
 
However, the main procedures should not be controlled with flags. 
 

For example, the command 'tk8 cluster aws -c -i -d' would be a complete contradiction in itself and is not visible at first glance.

Here the CLI parameters should be used and flags as additional control.    For example: 'tk8 cluster aws -f /myconfig.yml create'

**Comment by arashkaffamanesh** [comment]
Nice, yes, that way the user knows which config file she / he is using and is the standard way.
