### ISSUE TITLE
Add number of bastion hosts in the config options

### ISSUE THREAD

**Issue by arush-sal** [kubernauts/tk8#34]
@MuellerMH Can we also add the number of bastion hosts in the config as an option? 
As it really doesn't make sense to me to have 2 bastion hosts.

**Comment by arashkaffamanesh** [comment]
2 bastion hosts was apparently required for AWS install to support HA in different AZs, not sure if that's still the case, we could ask this in kubespray slack channel.

**Comment by MuellerMH** [comment]
arush [12:39 Uhr]
Yes, it can be configured and one bastion host will work.
