### ISSUE TITLE
Add release support through gorealeaser

### ISSUE THREAD

**Issue by arush-sal** [kubernauts/tk8#37]
We need to add support for [goreleaser](https://goreleaser.com/) for the next release as it not only ease the release process but does provide various other features such as built-in CI tests which supports all the major CI platforms and various release format including, but not limited to binary, deb, rpm, etc.

**Comment by arush-sal** [comment]
@MuellerMH Do we really even need this? I find the current release process pretty apt.

**Comment by MuellerMH** [comment]
For me, the current release process is perfect. In addition, I could not yet integrate the desired version into tk8 in the goreleaser. From my point of view this is not necessary.
