### ISSUE TITLE
Define code owners

### ISSUE THREAD

**Issue by arush-sal** [kubernauts/tk8#69]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
GitHub has the feature to clearly define code owners i.e which file in the repo is owned by whom.

**Describe alternatives you've considered**
none

**Additional context**
More Info can be found at: https://blog.github.com/2017-07-06-introducing-code-owners/

**Comment by arashkaffamanesh** [comment]
not needed
