### ISSUE TITLE
Create an SSH key and add to the cloud provider

### ISSUE THREAD

**Issue by arashkaffamanesh** [kubernauts/tk8#7]
As suggested by Arush:
Instead of depending on the user to provide their private SSH key, we should add an option in tk8 to create an SSH key, add that to the cloud provider(I am majorly talking AWS here but we can look into OpenStack also) and then use that key for our purpose just as Flux does it.

**Comment by arush-sal** [comment]
Fixed in fa19ac947045aea905c94c3567bd401259a0fcbe
