### ISSUE TITLE
TK8 and OpenStack

### ISSUE THREAD

**Issue by arashkaffamanesh** [kubernauts/tk8#77]
Kazimierz Sroka wrote to me:

I'm trying to set up kubernetes cluster using https://github.com/kubernauts/tk8 at v0.4.3.

I configure everything properly and after running tk8 cluster openstack --create terraform complete successfully but I can not ssh into bastion.
I am sure I am using correct key (there's only one on the openstack and when I create a new VM manually I can ssh properly). I am getting Permission denied when trying with root, centos, ubuntu or whatever i put in cluster.tfvars.

Could you help me debug this or point to someone who can?

I noticed that openstack folder was removed from master branch, why is that?

**Comment by kazz-s** [comment]
I'd like to add that tk8 cluster openstack --install fails with the same error, ansible is not able to ssh into VMs.

**Comment by arashkaffamanesh** [comment]
We could use infraly's implementation (pure kubeadm with ansible only):

https://github.com/infraly/k8s-on-openstack

**Comment by arashkaffamanesh** [comment]
OpenStack support is no more in our focus, perhaps later with Terraform Rancher Provider (?).
