### ISSUE TITLE
Add Bare Metal/Vagrant Support

### ISSUE THREAD

**Issue by petermetz** [kubernauts/tk8#91]
Is there any plans to support the pulling up of a cluster on bare metal/Vagrant based environments?

**Comment by arashkaffamanesh** [comment]
The bare-metal provisioner is here as an addon:
https://github.com/kubernauts/tk8-provisioner-baremetal
and as I remember it was tested on vagrant boxes as well.

Our own development cluster is currently built with RancherOS on bare metal running RKE on top with MetalLB support. This is the way which we recommend to go with at this time for bare metal.
