### ISSUE TITLE
tk8 cluster install rke doesn't work

### ISSUE THREAD

**Issue by arashkaffamanesh** [kubernauts/tk8#93]
tk8 cluster install rke doesn't work (e.g. as mentioned on this post):
https://blog.kubernauts.io/using-rke-as-a-cluster-provisioner-with-tk8-543c13a5ec35

**Comment by ishantanu** [comment]
As discussed in kubernauts #TK8 channel, the issue is not reproducible (after trying multiple times by me as well as Manuel). It is very much likely that the reported user has some misconfiguration related to required tools on his end.
